version: '3.5'

name: "my_infrastructure"

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: my_postrgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  migrate:
    image: migrate/migrate
    container_name: db_migrations
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    command:
      - -path
      - /migrations
      - -database
      - ${DB}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - up
      - ${VERSION}
    depends_on:
      - postgres