name: "db_project"

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: kinopoisk_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./migrations:/migrations
      - ./queries:/queries
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  python:
    image: python:3.11-alpine
    container_name: data_generator
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data_generation:/tmp/source
    working_dir: /tmp/source
    command: ["sh", "-c", "pip install -r requirements.txt && python main.py"]
